###INCLUDE_BEGIN### /daq/software/products/cetmodules/v3_24_01/config/package-config.cmake.preamble.in (2 passes)
########################################################################
# sbndqmConfig.cmake
#
#   Config for CMake project sbndqm 1.03.00.
#
# Generated by cetmodules 3.24.01 at Mon Nov 18 14:22:30 CST 2024.
#
# Compiled from:
#   /daq/software/products/cetmodules/v3_24_01/config/package-config.cmake.preamble.in
#   /daq/software/products/cetmodules/v3_24_01/config/package-config.cmake.init.in
#   genConfig/sbndqm-generated-config.cmake.vars.in
#   genConfig/sbndqm-generated-config.cmake.deps.in
#   genConfig/sbndqm-generated-config.cmake.targets.in
#   genConfig/sbndqm-generated-config.cmake.target_vars.in
#   /daq/software/products/cetmodules/v3_24_01/config/package-config.cmake.bottom.in
########################################################################
###INCLUDE_END###   /daq/software/products/cetmodules/v3_24_01/config/package-config.cmake.preamble.in

###INCLUDE_BEGIN### /daq/software/products/cetmodules/v3_24_01/config/package-config.cmake.init.in (2 passes)
###############################################################################
####### Expanded from @PACKAGE_INIT@ by configure_package_config_file() #######
####### Any changes to this file will be overwritten by the next CMake run ####
####### The input file was sbndqmConfig.cmake.in                            ########

get_filename_component(PACKAGE_PREFIX_DIR "${CMAKE_CURRENT_LIST_DIR}/" ABSOLUTE)

macro(set_and_check _var _file)
  set(${_var} "${_file}")
  if(NOT EXISTS "${_file}")
    message(FATAL_ERROR "File or directory ${_file} referenced by variable ${_var} does not exist !")
  endif()
endmacro()

macro(check_required_components _NAME)
  foreach(comp ${${_NAME}_FIND_COMPONENTS})
    if(NOT ${_NAME}_${comp}_FOUND)
      if(${_NAME}_FIND_REQUIRED_${comp})
        set(${_NAME}_FOUND FALSE)
      endif()
    endif()
  endforeach()
endmacro()

####################################################################################

# Make find_dependency() macro available.
include(CMakeFindDependencyMacro)
###INCLUDE_END###   /daq/software/products/cetmodules/v3_24_01/config/package-config.cmake.init.in

###INCLUDE_BEGIN### genConfig/sbndqm-generated-config.cmake.vars.in
####################################
# Package variable definitions.
####################################
# sbndqm_NAMESPACE
set(sbndqm_NAMESPACE "sbndqm")
# sbndqm_INCLUDE_DIR
if (EXISTS "${PACKAGE_PREFIX_DIR}/include")
  file(GLOB _sbndqm_TMP_DIR_ENTRIES "${PACKAGE_PREFIX_DIR}/include/*")
  if (_sbndqm_TMP_DIR_ENTRIES)
    set_and_check(sbndqm_INCLUDE_DIR "${PACKAGE_PREFIX_DIR}/include")
  endif()
  unset(_sbndqm_TMP_DIR_ENTRIES)
endif()
# sbndqm_LIBRARY_DIR
if (EXISTS "${PACKAGE_PREFIX_DIR}/slf7.x86_64.e26.prof/lib")
  file(GLOB _sbndqm_TMP_DIR_ENTRIES "${PACKAGE_PREFIX_DIR}/slf7.x86_64.e26.prof/lib/*")
  if (_sbndqm_TMP_DIR_ENTRIES)
    set_and_check(sbndqm_LIBRARY_DIR "${PACKAGE_PREFIX_DIR}/slf7.x86_64.e26.prof/lib")
  endif()
  unset(_sbndqm_TMP_DIR_ENTRIES)
endif()
# sbndqm_BIN_DIR
if (EXISTS "${PACKAGE_PREFIX_DIR}/slf7.x86_64.e26.prof/bin")
  file(GLOB _sbndqm_TMP_DIR_ENTRIES "${PACKAGE_PREFIX_DIR}/slf7.x86_64.e26.prof/bin/*")
  if (_sbndqm_TMP_DIR_ENTRIES)
    set_and_check(sbndqm_BIN_DIR "${PACKAGE_PREFIX_DIR}/slf7.x86_64.e26.prof/bin")
  endif()
  unset(_sbndqm_TMP_DIR_ENTRIES)
endif()
# sbndqm_FHICL_DIR
if (EXISTS "${PACKAGE_PREFIX_DIR}/fcl")
  file(GLOB _sbndqm_TMP_DIR_ENTRIES "${PACKAGE_PREFIX_DIR}/fcl/*")
  if (_sbndqm_TMP_DIR_ENTRIES)
    set_and_check(sbndqm_FHICL_DIR "${PACKAGE_PREFIX_DIR}/fcl")
  endif()
  unset(_sbndqm_TMP_DIR_ENTRIES)
endif()
# sbndqm_INSTALLED_SOURCE_DIR
if (EXISTS "${PACKAGE_PREFIX_DIR}/source")
  file(GLOB _sbndqm_TMP_DIR_ENTRIES "${PACKAGE_PREFIX_DIR}/source/*")
  if (_sbndqm_TMP_DIR_ENTRIES)
    set_and_check(sbndqm_INSTALLED_SOURCE_DIR "${PACKAGE_PREFIX_DIR}/source")
  endif()
  unset(_sbndqm_TMP_DIR_ENTRIES)
endif()
# sbndqm_FW_DIR
if (EXISTS "${PACKAGE_PREFIX_DIR}/scripts")
  file(GLOB _sbndqm_TMP_DIR_ENTRIES "${PACKAGE_PREFIX_DIR}/scripts/*")
  if (_sbndqm_TMP_DIR_ENTRIES)
    set_and_check(sbndqm_FW_DIR "${PACKAGE_PREFIX_DIR}/scripts")
  endif()
  unset(_sbndqm_TMP_DIR_ENTRIES)
endif()

####################################
# Package include directories.
####################################
if (IS_DIRECTORY "${PACKAGE_PREFIX_DIR}/include")
  # CMake convention:
  set(sbndqm_INCLUDE_DIRS "${PACKAGE_PREFIX_DIR}/include")
endif()

####################################
# Package library directories.
####################################
if (IS_DIRECTORY "${PACKAGE_PREFIX_DIR}/slf7.x86_64.e26.prof/lib")
  # CMake convention:
  set(sbndqm_LIBRARY_DIRS "${PACKAGE_PREFIX_DIR}/slf7.x86_64.e26.prof/lib")
endif()
###INCLUDE_END###   genConfig/sbndqm-generated-config.cmake.vars.in

###INCLUDE_BEGIN### genConfig/sbndqm-generated-config.cmake.deps.in
####################################
# Transitive dependencies.
####################################
set(_sbndqm_PACKAGE_PREFIX_DIR "${PACKAGE_PREFIX_DIR}")
find_dependency(artdaq_core REQUIRED)
find_dependency(sbndaq_online REQUIRED)
set(PACKAGE_PREFIX_DIR "${_sbndqm_PACKAGE_PREFIX_DIR}")
unset(_sbndqm_PACKAGE_PREFIX_DIR)
###INCLUDE_END###   genConfig/sbndqm-generated-config.cmake.deps.in

###INCLUDE_BEGIN### genConfig/sbndqm-generated-config.cmake.targets.in
####################################
# Exported targets, and package components.
####################################

##################
# Automatically-generated runtime targets: sbndqm
##################
include("${CMAKE_CURRENT_LIST_DIR}/sbndqmTargets.cmake")
foreach (component IN LISTS sbndqm_FIND_COMPONENTS)
  include("${CMAKE_CURRENT_LIST_DIR}/sbndqmTargets_${component}.cmake")
endforeach()

##################
# Manually-generated non-runtime targets.
##################
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach (_expectedTarget IN ITEMS
    sbndqm::startOM.sh)
  list(APPEND _expectedTargets ${_expectedTarget})
  if (NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if (TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if ("${_targetsDefined}" STREQUAL "${_expectedTargets}")  # Nothing to do.
elseif ("${_targetsDefined}" STREQUAL "") # Need to define targets.
  add_executable(sbndqm::startOM.sh IMPORTED)
  set_target_properties(sbndqm::startOM.sh
    PROPERTIES IMPORTED_LOCATION "${PACKAGE_PREFIX_DIR}/slf7.x86_64.e26.prof/bin/startOM.sh")
else()
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.
Targets Defined: ${_targetsDefined}
Targets not yet defined: ${_targetsNotDefined}
")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)
###INCLUDE_END###   genConfig/sbndqm-generated-config.cmake.targets.in

###INCLUDE_BEGIN### genConfig/sbndqm-generated-config.cmake.target_vars.in
####################################
# Old cetbuildtools-style target variables.
####################################
if (${CETMODULES_CURRENT_PROJECT_NAME}_OLD_STYLE_CONFIG_VARS OR # Per-dependent setting.
 cetbuildtools_UPS_VERSION OR # Backward-compatibility.
 ${CETMODULES_CURRENT_PROJECT_NAME}_UPS_BUILD_ONLY_DEPENDENCIES
 MATCHES "(^|;)cetbuildtools(;|$)")
  set(SBNDQM_DECODE_TPC_SBND_DQMCHANNELMAP_TPCDQMCHANNELIDANA_MODULE sbndqm::Decode_TPC_SBND_DQMChannelMap_TPCDQMChannelIDAna_module)
  set(SBNDQM_DECODE_TPC_SBND_DQMCHANNELMAP_TPCDQMCHANNELMAPSERVICE_SERVICE sbndqm::Decode_TPC_SBND_DQMChannelMap_TPCDQMChannelMapService_service)
  set(SBNDQM_DECODE_TPC_SBND_SBNDDQMTPCDECODER_MODULE sbndqm::Decode_TPC_SBND_SBNDDQMTPCDecoder_module)
  set(SBNDQM_DECODE_TPC_SBND_DICT sbndqm::Decode_TPC_SBND_dict)
  set(SBNDQM_DECODE_TPC_DICT sbndqm::Decode_TPC_dict)
  set(SBNDQM_DECODE_PMT_PMTDECODEDATA sbndqm::Decode_PMT_PMTDecodeData)
  set(SBNDQM_DECODE_PMT_PMTDECODEDATA_DICT sbndqm::Decode_PMT_PMTDecodeData_dict)
  set(SBNDQM_DECODE_PMT_ICARUS_DAQDECODERICARUSPMT_MODULE sbndqm::Decode_PMT_ICARUS_DaqDecoderIcarusPMT_module)
  set(SBNDQM_DECODE_PMT_SBND_DAQDECODERSBNDPMT_MODULE sbndqm::Decode_PMT_SBND_DaqDecoderSBNDPMT_module)
  set(SBNDQM_DECODE_TRIGGER sbndqm::Decode_Trigger)
  set(SBNDQM_DECODE_TRIGGER_DAQDECODERICARUSTRIGGER_MODULE sbndqm::Decode_Trigger_DaqDecoderIcarusTrigger_module)
  set(SBNDQM_DECODE_MODE sbndqm::Decode_Mode)
  set(SBNDQM_DQMANALYSIS_PMT_ICARUS_CAENV1730STREAMS_MODULE sbndqm::dqmAnalysis_PMT_ICARUS_CAENV1730Streams_module)
  set(SBNDQM_DQMANALYSIS_PMT_ICARUS_BEAMTIMINGSTREAMS_MODULE sbndqm::dqmAnalysis_PMT_ICARUS_BeamTimingStreams_module)
  set(SBNDQM_DQMANALYSIS_PMT_SBND_CAENV1730STREAMSSBND_MODULE sbndqm::dqmAnalysis_PMT_SBND_CAENV1730StreamsSBND_module)
  set(SBNDQM_DQMANALYSIS_TPC_ONLINEFILTERS_SNAPSHOTFILTER_MODULE sbndqm::dqmAnalysis_TPC_OnlineFilters_SnapshotFilter_module)
  set(SBNDQM_DQMANALYSIS_TPC_ICARUS_OFFLINEANALYSIS_MODULE sbndqm::dqmAnalysis_TPC_ICARUS_OfflineAnalysis_module)
  set(SBNDQM_DQMANALYSIS_TPC_ICARUS_TPCWAVEFORMCREATOR_MODULE sbndqm::dqmAnalysis_TPC_ICARUS_TPCWaveformCreator_module)
  set(SBNDQM_DQMANALYSIS_TPC_ICARUS_ONLINEANALYSIS_MODULE sbndqm::dqmAnalysis_TPC_ICARUS_OnlineAnalysis_module)
  set(SBNDQM_DQMANALYSIS_TPC_ICARUS_TPCPURITYDQMSENDER_MODULE sbndqm::dqmAnalysis_TPC_ICARUS_TPCPurityDQMSender_module)
  set(SBNDQM_DQMANALYSIS_TPC_ICARUS_TPCWAVEFORMANDFFTREDIS_MODULE sbndqm::dqmAnalysis_TPC_ICARUS_TPCWaveformAndFftRedis_module)
  set(SBNDQM_DQMANALYSIS_TPC_SBND_OFFLINEANALYSISSBND_MODULE sbndqm::dqmAnalysis_TPC_SBND_OfflineAnalysisSBND_module)
  set(SBNDQM_DQMANALYSIS_TPC_SBND_TPCWAVEFORMCREATORSBND_MODULE sbndqm::dqmAnalysis_TPC_SBND_TPCWaveformCreatorSBND_module)
  set(SBNDQM_DQMANALYSIS_TPC_SBND_ONLINEANALYSISSBND_MODULE sbndqm::dqmAnalysis_TPC_SBND_OnlineAnalysisSBND_module)
  set(SBNDQM_DQMANALYSIS_TPC_SBND_TPCWAVEFORMANDFFTREDISSBND_MODULE sbndqm::dqmAnalysis_TPC_SBND_TPCWaveformAndFftRedisSBND_module)
  set(SBNDQM_DQMANALYSIS_TPC_SBND_ONLINEEVDSBND_MODULE sbndqm::dqmAnalysis_TPC_SBND_OnlineEvdSBND_module)
  set(SBNDQM_DQMANALYSIS_TPC_DICT sbndqm::dqmAnalysis_TPC_dict)
  set(SBNDQM_TPCANALYSIS_SBN sbndqm::tpcAnalysis_SBN)
  set(SBNDQM_DQMANALYSIS_TRIGGER_ICARUS_TRIGGERSTREAMS_MODULE sbndqm::dqmAnalysis_Trigger_ICARUS_TriggerStreams_module)
  set(SBNDQM_DQMANALYSIS_TRIGGER_SBND_PTBDQM_MODULE sbndqm::dqmAnalysis_Trigger_SBND_PTBdqm_module)
  set(SBNDQM_DQMANALYSIS_NEVIS_NEVISPRODUCTIONTEST_MODULE sbndqm::dqmAnalysis_Nevis_NevisProductionTest_module)
  set(SBNDQM_DQMANALYSIS_CRT_ICARUS_BERNCRTDQM_MODULE sbndqm::dqmAnalysis_CRT_ICARUS_BernCRTdqm_module)
  set(SBNDQM_DQMANALYSIS_CRT_SBND_BERNCRTDQMSBND_MODULE sbndqm::dqmAnalysis_CRT_SBND_BernCRTdqmSBND_module)
  set(SBNDQM_DQMANALYSIS_META_REPORTMETADATA_MODULE sbndqm::dqmAnalysis_Meta_ReportMetadata_module)
  set(SBNDQM_DQMANALYSIS_EXAMPLE_EXAMPLETIMESTREAM_MODULE sbndqm::dqmAnalysis_example_ExampleTimeStream_module)
  set(SBNDQM_DQMANALYSIS_EXAMPLE_EXAMPLEDATABASESTORAGE_MODULE sbndqm::dqmAnalysis_example_ExampleDatabaseStorage_module)
  set(SBNDQM_DQMANALYSIS_EXAMPLE_EXAMPLEALARM_MODULE sbndqm::dqmAnalysis_example_ExampleAlarm_module)
  set(SBNDQM_DQMANALYSIS_FRAGMENTANA_FRAGMENTDQMANA_MODULE sbndqm::dqmAnalysis_FragmentAna_FragmentDQMAna_module)
  set(SBNDQM_DQMANALYSIS_TIMING_SPECTDCSTREAMS_MODULE sbndqm::dqmAnalysis_Timing_SPECTDCStreams_module)
endif()
###INCLUDE_END###   genConfig/sbndqm-generated-config.cmake.target_vars.in

###INCLUDE_BEGIN### /daq/software/products/cetmodules/v3_24_01/config/package-config.cmake.bottom.in
# Check package components.
check_required_components(sbndqm)
###INCLUDE_END###   /daq/software/products/cetmodules/v3_24_01/config/package-config.cmake.bottom.in
