###INCLUDE_BEGIN### /daq/software/products/cetmodules/v3_24_01/config/package-config.cmake.preamble.in (2 passes)
########################################################################
# sbndaq_onlineConfig.cmake
#
#   Config for CMake project sbndaq_online 1.01.00.
#
# Generated by cetmodules 3.24.01 at Mon Nov 18 14:22:25 CST 2024.
#
# Compiled from:
#   /daq/software/products/cetmodules/v3_24_01/config/package-config.cmake.preamble.in
#   /daq/software/products/cetmodules/v3_24_01/config/package-config.cmake.init.in
#   genConfig/sbndaq_online-generated-config.cmake.vars.in
#   genConfig/sbndaq_online-generated-config.cmake.deps.in
#   genConfig/sbndaq_online-generated-config.cmake.targets.in
#   genConfig/sbndaq_online-generated-config.cmake.target_vars.in
#   /daq/software/products/cetmodules/v3_24_01/config/package-config.cmake.bottom.in
########################################################################
###INCLUDE_END###   /daq/software/products/cetmodules/v3_24_01/config/package-config.cmake.preamble.in

###INCLUDE_BEGIN### /daq/software/products/cetmodules/v3_24_01/config/package-config.cmake.init.in (2 passes)
###############################################################################
####### Expanded from @PACKAGE_INIT@ by configure_package_config_file() #######
####### Any changes to this file will be overwritten by the next CMake run ####
####### The input file was sbndaq_onlineConfig.cmake.in                            ########

get_filename_component(PACKAGE_PREFIX_DIR "${CMAKE_CURRENT_LIST_DIR}/" ABSOLUTE)

macro(set_and_check _var _file)
  set(${_var} "${_file}")
  if(NOT EXISTS "${_file}")
    message(FATAL_ERROR "File or directory ${_file} referenced by variable ${_var} does not exist !")
  endif()
endmacro()

macro(check_required_components _NAME)
  foreach(comp ${${_NAME}_FIND_COMPONENTS})
    if(NOT ${_NAME}_${comp}_FOUND)
      if(${_NAME}_FIND_REQUIRED_${comp})
        set(${_NAME}_FOUND FALSE)
      endif()
    endif()
  endforeach()
endmacro()

####################################################################################

# Make find_dependency() macro available.
include(CMakeFindDependencyMacro)
###INCLUDE_END###   /daq/software/products/cetmodules/v3_24_01/config/package-config.cmake.init.in

###INCLUDE_BEGIN### genConfig/sbndaq_online-generated-config.cmake.vars.in
####################################
# Package variable definitions.
####################################
# sbndaq_online_NAMESPACE
set(sbndaq_online_NAMESPACE "sbndaq_online")
# sbndaq_online_INCLUDE_DIR
if (EXISTS "${PACKAGE_PREFIX_DIR}/include")
  file(GLOB _sbndaq_online_TMP_DIR_ENTRIES "${PACKAGE_PREFIX_DIR}/include/*")
  if (_sbndaq_online_TMP_DIR_ENTRIES)
    set_and_check(sbndaq_online_INCLUDE_DIR "${PACKAGE_PREFIX_DIR}/include")
  endif()
  unset(_sbndaq_online_TMP_DIR_ENTRIES)
endif()
# sbndaq_online_LIBRARY_DIR
if (EXISTS "${PACKAGE_PREFIX_DIR}/slf7.x86_64.e26.prof/lib")
  file(GLOB _sbndaq_online_TMP_DIR_ENTRIES "${PACKAGE_PREFIX_DIR}/slf7.x86_64.e26.prof/lib/*")
  if (_sbndaq_online_TMP_DIR_ENTRIES)
    set_and_check(sbndaq_online_LIBRARY_DIR "${PACKAGE_PREFIX_DIR}/slf7.x86_64.e26.prof/lib")
  endif()
  unset(_sbndaq_online_TMP_DIR_ENTRIES)
endif()
# sbndaq_online_BIN_DIR
if (EXISTS "${PACKAGE_PREFIX_DIR}/slf7.x86_64.e26.prof/bin")
  file(GLOB _sbndaq_online_TMP_DIR_ENTRIES "${PACKAGE_PREFIX_DIR}/slf7.x86_64.e26.prof/bin/*")
  if (_sbndaq_online_TMP_DIR_ENTRIES)
    set_and_check(sbndaq_online_BIN_DIR "${PACKAGE_PREFIX_DIR}/slf7.x86_64.e26.prof/bin")
  endif()
  unset(_sbndaq_online_TMP_DIR_ENTRIES)
endif()
# sbndaq_online_INSTALLED_SOURCE_DIR
if (EXISTS "${PACKAGE_PREFIX_DIR}/source")
  file(GLOB _sbndaq_online_TMP_DIR_ENTRIES "${PACKAGE_PREFIX_DIR}/source/*")
  if (_sbndaq_online_TMP_DIR_ENTRIES)
    set_and_check(sbndaq_online_INSTALLED_SOURCE_DIR "${PACKAGE_PREFIX_DIR}/source")
  endif()
  unset(_sbndaq_online_TMP_DIR_ENTRIES)
endif()

####################################
# Package include directories.
####################################
if (IS_DIRECTORY "${PACKAGE_PREFIX_DIR}/include")
  # CMake convention:
  set(sbndaq_online_INCLUDE_DIRS "${PACKAGE_PREFIX_DIR}/include")
endif()

####################################
# Package library directories.
####################################
if (IS_DIRECTORY "${PACKAGE_PREFIX_DIR}/slf7.x86_64.e26.prof/lib")
  # CMake convention:
  set(sbndaq_online_LIBRARY_DIRS "${PACKAGE_PREFIX_DIR}/slf7.x86_64.e26.prof/lib")
endif()
###INCLUDE_END###   genConfig/sbndaq_online-generated-config.cmake.vars.in

###INCLUDE_BEGIN### genConfig/sbndaq_online-generated-config.cmake.deps.in
###INCLUDE_END###   genConfig/sbndaq_online-generated-config.cmake.deps.in

###INCLUDE_BEGIN### genConfig/sbndaq_online-generated-config.cmake.targets.in
####################################
# Exported targets, and package components.
####################################

##################
# Automatically-generated runtime targets: sbndaq_online
##################
include("${CMAKE_CURRENT_LIST_DIR}/sbndaq_onlineTargets.cmake")
foreach (component IN LISTS sbndaq_online_FIND_COMPONENTS)
  include("${CMAKE_CURRENT_LIST_DIR}/sbndaq_onlineTargets_${component}.cmake")
endforeach()
###INCLUDE_END###   genConfig/sbndaq_online-generated-config.cmake.targets.in

###INCLUDE_BEGIN### genConfig/sbndaq_online-generated-config.cmake.target_vars.in
####################################
# Old cetbuildtools-style target variables.
####################################
if (${CETMODULES_CURRENT_PROJECT_NAME}_OLD_STYLE_CONFIG_VARS OR # Per-dependent setting.
 cetbuildtools_UPS_VERSION OR # Backward-compatibility.
 ${CETMODULES_CURRENT_PROJECT_NAME}_UPS_BUILD_ONLY_DEPENDENCIES
 MATCHES "(^|;)cetbuildtools(;|$)")
  set(SBNDAQ_ONLINE_HIREDIS sbndaq_online::hiredis)
  set(SBNDAQ_ONLINE_REDIS_CONNECTION sbndaq_online::redis_connection)
  set(SBNDAQ_ONLINE_SBNDAQ-ONLINE_REDIS-CONNECT_REDISCONNECTION_SERVICE sbndaq_online::sbndaq-online_redis-connect_RedisConnection_service)
  set(SBNDAQ_ONLINE_SBNDAQ-ONLINE_REDIS-PLUGIN_REDIS_METRIC sbndaq_online::sbndaq-online_redis-plugin_redis_metric)
  set(SBNDAQ_ONLINE_STORAGE sbndaq_online::storage)
  set(SBNDAQ_ONLINE_SBNDAQ-ONLINE_HELPERS_INITMETRICMANAGER_SERVICE sbndaq_online::sbndaq-online_helpers_InitMetricManager_service)
endif()
###INCLUDE_END###   genConfig/sbndaq_online-generated-config.cmake.target_vars.in

###INCLUDE_BEGIN### /daq/software/products/cetmodules/v3_24_01/config/package-config.cmake.bottom.in
# Check package components.
check_required_components(sbndaq_online)
###INCLUDE_END###   /daq/software/products/cetmodules/v3_24_01/config/package-config.cmake.bottom.in
