# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.25)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS sbndaq_online::hiredis sbndaq_online::redis_connection sbndaq_online::sbndaq-online_redis-connect_RedisConnection_service sbndaq_online::sbndaq-online_redis-connect_RedisConnection_service_reg sbndaq_online::sbndaq-online_redis-plugin_redis_metric sbndaq_online::storage sbndaq_online::sbndaq-online_helpers_InitMetricManager_service)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target sbndaq_online::hiredis
add_library(sbndaq_online::hiredis SHARED IMPORTED)

set_target_properties(sbndaq_online::hiredis PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/nfs/sbnddqm/DQM_DevAreas/CRT_DQM_NP_29Oct2024/build_slf7.x86_64/sbndaq_online;/home/nfs/sbnddqm/DQM_DevAreas/CRT_DQM_NP_29Oct2024/srcs/sbndaq_online"
)

# Create imported target sbndaq_online::redis_connection
add_library(sbndaq_online::redis_connection SHARED IMPORTED)

set_target_properties(sbndaq_online::redis_connection PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/nfs/sbnddqm/DQM_DevAreas/CRT_DQM_NP_29Oct2024/build_slf7.x86_64/sbndaq_online;/home/nfs/sbnddqm/DQM_DevAreas/CRT_DQM_NP_29Oct2024/srcs/sbndaq_online"
  INTERFACE_LINK_LIBRARIES "sbndaq_online::hiredis;artdaq_utilities::artdaq-utilities_Plugins;art::Framework_Core;art::Framework_Principal;art::Framework_Services_Registry;art::Framework_Services_System_FileCatalogMetadata_service;art::Persistency_Common;art::Persistency_Provenance;canvas::canvas;art_root_io::tfile_support;art_root_io::TFileService_service;ROOT::Core;art::Utilities;messagefacility::MF_MessageLogger;fhiclcpp::fhiclcpp;cetlib::cetlib;cetlib_except::cetlib_except"
)

# Create imported target sbndaq_online::sbndaq-online_redis-connect_RedisConnection_service
add_library(sbndaq_online::sbndaq-online_redis-connect_RedisConnection_service SHARED IMPORTED)

set_target_properties(sbndaq_online::sbndaq-online_redis-connect_RedisConnection_service PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/nfs/sbnddqm/DQM_DevAreas/CRT_DQM_NP_29Oct2024/build_slf7.x86_64/sbndaq_online;/home/nfs/sbnddqm/DQM_DevAreas/CRT_DQM_NP_29Oct2024/srcs/sbndaq_online"
  INTERFACE_LINK_LIBRARIES "sbndaq_online::redis_connection;art_plugin_types::serviceDeclaration"
)

# Create imported target sbndaq_online::sbndaq-online_redis-connect_RedisConnection_service_reg
add_library(sbndaq_online::sbndaq-online_redis-connect_RedisConnection_service_reg MODULE IMPORTED)

set_target_properties(sbndaq_online::sbndaq-online_redis-connect_RedisConnection_service_reg PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/nfs/sbnddqm/DQM_DevAreas/CRT_DQM_NP_29Oct2024/build_slf7.x86_64/sbndaq_online;/home/nfs/sbnddqm/DQM_DevAreas/CRT_DQM_NP_29Oct2024/srcs/sbndaq_online"
)

# Create imported target sbndaq_online::sbndaq-online_redis-plugin_redis_metric
add_library(sbndaq_online::sbndaq-online_redis-plugin_redis_metric SHARED IMPORTED)

set_target_properties(sbndaq_online::sbndaq-online_redis-plugin_redis_metric PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/nfs/sbnddqm/DQM_DevAreas/CRT_DQM_NP_29Oct2024/build_slf7.x86_64/sbndaq_online;/home/nfs/sbnddqm/DQM_DevAreas/CRT_DQM_NP_29Oct2024/srcs/sbndaq_online"
  INTERFACE_LINK_LIBRARIES "artdaq_utilities::artdaq-utilities_Plugins;sbndaq_online::redis_connection;fhiclcpp::fhiclcpp;cetlib::cetlib;cetlib_except::cetlib_except;messagefacility::MF_MessageLogger"
)

# Create imported target sbndaq_online::storage
add_library(sbndaq_online::storage SHARED IMPORTED)

set_target_properties(sbndaq_online::storage PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/nfs/sbnddqm/DQM_DevAreas/CRT_DQM_NP_29Oct2024/build_slf7.x86_64/sbndaq_online;/home/nfs/sbnddqm/DQM_DevAreas/CRT_DQM_NP_29Oct2024/srcs/sbndaq_online"
  INTERFACE_LINK_LIBRARIES "sbndaq_online::redis_connection;sbndaq_online::hiredis;ROOT::Core;ROOT::ASImage;ROOT::Gpad;/daq/software/products/jsoncpp/v1_9_5a/Linux64bit+3.10-2.17-e26-prof/lib/libjsoncpp.so"
)

# Create imported target sbndaq_online::sbndaq-online_helpers_InitMetricManager_service
add_library(sbndaq_online::sbndaq-online_helpers_InitMetricManager_service SHARED IMPORTED)

set_target_properties(sbndaq_online::sbndaq-online_helpers_InitMetricManager_service PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/nfs/sbnddqm/DQM_DevAreas/CRT_DQM_NP_29Oct2024/build_slf7.x86_64/sbndaq_online;/home/nfs/sbnddqm/DQM_DevAreas/CRT_DQM_NP_29Oct2024/srcs/sbndaq_online"
  INTERFACE_LINK_LIBRARIES "sbndaq_online::storage;art_plugin_types::serviceDeclaration"
)

# Import target "sbndaq_online::hiredis" for configuration "RelWithDebInfo"
set_property(TARGET sbndaq_online::hiredis APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(sbndaq_online::hiredis PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/nfs/sbnddqm/DQM_DevAreas/CRT_DQM_NP_29Oct2024/build_slf7.x86_64/sbndaq_online/slf7.x86_64.e26.prof/lib/libsbndaq_online_hiredis.so"
  IMPORTED_SONAME_RELWITHDEBINFO "libsbndaq_online_hiredis.so"
  )

# Import target "sbndaq_online::redis_connection" for configuration "RelWithDebInfo"
set_property(TARGET sbndaq_online::redis_connection APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(sbndaq_online::redis_connection PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/nfs/sbnddqm/DQM_DevAreas/CRT_DQM_NP_29Oct2024/build_slf7.x86_64/sbndaq_online/slf7.x86_64.e26.prof/lib/libsbndaq_online_redis_connection.so"
  IMPORTED_SONAME_RELWITHDEBINFO "libsbndaq_online_redis_connection.so"
  )

# Import target "sbndaq_online::sbndaq-online_redis-connect_RedisConnection_service" for configuration "RelWithDebInfo"
set_property(TARGET sbndaq_online::sbndaq-online_redis-connect_RedisConnection_service APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(sbndaq_online::sbndaq-online_redis-connect_RedisConnection_service PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/nfs/sbnddqm/DQM_DevAreas/CRT_DQM_NP_29Oct2024/build_slf7.x86_64/sbndaq_online/slf7.x86_64.e26.prof/lib/libsbndaq-online_redis-connect_RedisConnection.so"
  IMPORTED_SONAME_RELWITHDEBINFO "libsbndaq-online_redis-connect_RedisConnection.so"
  )

# Import target "sbndaq_online::sbndaq-online_redis-connect_RedisConnection_service_reg" for configuration "RelWithDebInfo"
set_property(TARGET sbndaq_online::sbndaq-online_redis-connect_RedisConnection_service_reg APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(sbndaq_online::sbndaq-online_redis-connect_RedisConnection_service_reg PROPERTIES
  IMPORTED_COMMON_LANGUAGE_RUNTIME_RELWITHDEBINFO ""
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/nfs/sbnddqm/DQM_DevAreas/CRT_DQM_NP_29Oct2024/build_slf7.x86_64/sbndaq_online/slf7.x86_64.e26.prof/lib/libsbndaq-online_redis-connect_RedisConnection_service.so"
  IMPORTED_NO_SONAME_RELWITHDEBINFO "TRUE"
  )

# Import target "sbndaq_online::sbndaq-online_redis-plugin_redis_metric" for configuration "RelWithDebInfo"
set_property(TARGET sbndaq_online::sbndaq-online_redis-plugin_redis_metric APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(sbndaq_online::sbndaq-online_redis-plugin_redis_metric PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/nfs/sbnddqm/DQM_DevAreas/CRT_DQM_NP_29Oct2024/build_slf7.x86_64/sbndaq_online/slf7.x86_64.e26.prof/lib/libsbndaq-online_redis-plugin_redis_metric.so"
  IMPORTED_SONAME_RELWITHDEBINFO "libsbndaq-online_redis-plugin_redis_metric.so"
  )

# Import target "sbndaq_online::storage" for configuration "RelWithDebInfo"
set_property(TARGET sbndaq_online::storage APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(sbndaq_online::storage PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/nfs/sbnddqm/DQM_DevAreas/CRT_DQM_NP_29Oct2024/build_slf7.x86_64/sbndaq_online/slf7.x86_64.e26.prof/lib/libsbndaq_online_storage.so"
  IMPORTED_SONAME_RELWITHDEBINFO "libsbndaq_online_storage.so"
  )

# Import target "sbndaq_online::sbndaq-online_helpers_InitMetricManager_service" for configuration "RelWithDebInfo"
set_property(TARGET sbndaq_online::sbndaq-online_helpers_InitMetricManager_service APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(sbndaq_online::sbndaq-online_helpers_InitMetricManager_service PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/nfs/sbnddqm/DQM_DevAreas/CRT_DQM_NP_29Oct2024/build_slf7.x86_64/sbndaq_online/slf7.x86_64.e26.prof/lib/libsbndaq-online_helpers_InitMetricManager_service.so"
  IMPORTED_SONAME_RELWITHDEBINFO "libsbndaq-online_helpers_InitMetricManager_service.so"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
